name-template: 'Draft'
categories:
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'bugfix'
    - title: '🏠 Internal use'
      labels:
        - 'chore'
    - title: '🧰 Refactor'
      labels:
        - 'refactor'
    - title: ' 🤖 Dependencies'
      labels:
        - 'dependencies'
change-template: '- [] #$NUMBER $TITLE @$AUTHOR'
template: |
  $CHANGES
