name: main_to_develop

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    name: Create PullRequest
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create PullRequest
        shell: bash
        run: |
          gh pr create --base develop --head main --title "main -> develop" --body "" --reviewer ${{ github.event.sender.login }},shintaro-matsudo || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
