name: Create Release Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Get tag
      #   id: tag
      #   run: |
      #     TAG=$(TODAY=v`date +%Y%m%d`; git tag | grep -e ${TODAY} | cat - <(echo "${TODAY}_00") | sort | tail -1 | awk -F "_" "{cnt=\$2+1}{printf \"%s_%02d\", \$1, cnt}")
      #     echo ::set-output name=TAG::$TAG
      #   env:
      #     TZ: Asia/Tokyo

      - name: Create or update a release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
