name: Merge main to release & Draft release note

on:
  repository_dispatch:
    types: [release_preparation]

jobs:
  merge_main_to_release:
    name: Merge main to release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release

      - name: Create title
        id: create-title
        run: |
          TITLE=RELEASE`TZ=UTC-9 date +%Y%m%d`
          echo "title=$TITLE" >> $GITHUB_OUTPUT

      - name: Create previous tag
        id: create-previous-tag
        run: |
          TAG=$(git tag | tail -1)
          echo $TAG
          echo "previous_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create tag
        id: create-tag
        run: |
          TAG=v$(TODAY=`TZ=UTC-9 date +%Y%m%d`; git tag | grep -e ${TODAY} | cat - <(echo "${TODAY}_00") | sort | tail -1 | awk -F "_" "{cnt=\$2+1}{printf \"%s_%02d\", \$1, cnt}")
          echo $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create body
        id: create-body
        run: |
          BODY=${git log --merges --reverse  --format='%s' ${{ steps.create-previous-tag.outputs.previous_tag }}..${{ steps.create-tag.outputs.tag }} | grep 'Merge pull request #' | sed -e 's/Merge pull request/-/g' | awk '{ sub(" from.*$",""); print $0; }'}
          echo "body=$BODY" >> $GITHUB_OUTPUT

      - name: Create PullRequest
        shell: bash
        run: |
          gh pr create --base release --head main --title "${{ steps.create-title.outputs.title }}" --body "${{ steps.create-body.outputs.body }}" --reviewer ${{ github.event.sender.login }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PullRequest
        shell: bash
        run: |
          gh pr merge main --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Draft release note
        shell: bash
        run: |
          gh release create ${{ steps.create-tag.outputs.tag }} --draft --target release --title ${{ steps.create-tag.outputs.tag }} --generate-notes --notes-start-tag ${{ steps.create-previous-tag.outputs.previous_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
