name: Execute staging release

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [staging_release]

jobs:
  execute_staging_release:
    name: Execute staging release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release

      - name: Create tag
        id: create-tag
        run: |
          TAG=RELEASE`date +%Y%m%d`
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create and Merge PullRequest
        shell: bash
        run: |
          gh pr create --base release --head main --title "${{ steps.create-tag.outputs.tag }}" --body "${{ GITHUB_SHA::8 }}" --reviewer ${{ github.event.sender.login }}
          gh pr merge main --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
