name: Create Note
on:
  push:
    branches: [main]
  pull_request:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Note
        uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const pr = gh release view v20230103_01 --json body --jq . | sed -e 's/{"body":"//g' | sed -e 's/"}//g'
            console.log(pr)
            return pr
          result-encoding: string
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
