name: Create Note
on:
  push:
    branches: [main]
  pull_request:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Note
        id: result
        run: |
          PR=`gh release view v20230103_01 --json body --jq . | sed -e 's/{"body":"//g' | sed -e 's/"}//g'`
          echo $PR
          echo 'NOTE<<EOF' >> $GITHUB_OUTPUT
          echo $PR >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get result
        run: echo "${{steps.result.outputs.NOTE}}"
